services:
  api:
    image: pranavthegoat/todo-api:latest
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./api/.env

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: