services:
  api:
    build: ./api
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - PORT=3000
    volumes:
      - ./api:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: